USE [mchn]

IF OBJECT_ID('[sch_mchn].[T_PRICING_RATE]', 'U') IS NOT NULL 
  DROP TABLE  [sch_mchn].[T_PRICING_RATE]; 

IF OBJECT_ID('[sch_mchn].[T_MACHINE_EDITION_CLAUSE]', 'U') IS NOT NULL 
  DROP TABLE [sch_mchn].[T_MACHINE_EDITION_CLAUSE]; 

IF OBJECT_ID('[sch_mchn].[T_EDITION_CLAUSE]', 'U') IS NOT NULL 
  DROP TABLE [sch_mchn].[T_EDITION_CLAUSE]; 

IF OBJECT_ID('[sch_mchn].[T_FAMILYT_MACHINE_SPECIFICATION]', 'U') IS NOT NULL 
  DROP TABLE [sch_mchn].[T_FAMILYT_MACHINE_SPECIFICATION]; 

IF OBJECT_ID('[sch_mchn].[T_FAMILY]', 'U') IS NOT NULL 
  DROP TABLE [sch_mchn].[T_FAMILY];

IF OBJECT_ID('[sch_mchn].[T_MACHINE_SPECIFICATION]', 'U') IS NOT NULL 
  DROP TABLE [sch_mchn].[T_MACHINE_SPECIFICATION]; 
