USE [mchn]
GO

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[sch_mchn].[T_FAMILY]') AND name='IX_FAMILY_CODE_SUBCODE')
   DROP INDEX [IX_FAMILY_CODE_SUBCODE] ON [sch_mchn].[T_FAMILY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_FAMILY_CODE_SUBCODE] ON [sch_mchn].[T_FAMILY]
(
	[CODE] ASC,
	[SUB_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO 

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[sch_mchn].[T_MACHINE_SPECIFICATION]') AND name='IX_T_MACHINE_SPECIFICATION_CODE_END_DATETIME_SUBSCRIPTION_PERIOD')
   DROP INDEX [IX_T_MACHINE_SPECIFICATION_CODE_END_DATETIME_SUBSCRIPTION_PERIOD] ON [sch_mchn].[T_MACHINE_SPECIFICATION]
GO

CREATE NONCLUSTERED INDEX [IX_T_MACHINE_SPECIFICATION_CODE_END_DATETIME_SUBSCRIPTION_PERIOD] ON [sch_mchn].[T_MACHINE_SPECIFICATION]
(
	[CODE] ASC,
	[END_DATETIME_SUBSCRIPTION_PERIOD] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

/****** Object:  Index [IX_T_MACHINE_SPECIFICATION_CODE]    Script Date: 07/10/2021 16:59:27 ******/
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[sch_mchn].[T_MACHINE_EDITION_CLAUSE]') AND name='IX_T_MACHINE_EDITION_CLAUSE_CODE')
   DROP INDEX [IX_T_MACHINE_EDITION_CLAUSE_CODE] ON [sch_mchn].[T_MACHINE_EDITION_CLAUSE]
GO

/****** Object:  Index [IX_T_MACHINE_SPECIFICATION_CODE]    Script Date: 07/10/2021 16:59:27 ******/
CREATE NONCLUSTERED INDEX [IX_T_MACHINE_EDITION_CLAUSE_CODE] ON [sch_mchn].[T_MACHINE_EDITION_CLAUSE]
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

