-------------------------------------------------------------------------
-- Auteur    : S838981
-- Date      : 08/12/2021
-- Base      : Sql Server - mchn
-- Version	 : 1.0.0
-- Projet	 : OSE BDM
-- Objet     : rechargement des clauses éditions
-------------------------------------------------------------------------


USE [mchn]

delete from [sch_mchn].[T_EDITION_CLAUSE];

INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA09','Conditions de garantie transport des ordinateurs portables ',0,'Par extension aux Conditions générales, les micro-ordinateurs portables et les tablettes tactiles sont garantis en tous lieux dans le monde entier, sous réserve des conditions de garantie transport définies ci-après.' + CHAR(13)  + CHAR(13) + 'Conditions de garantie transport :' + CHAR(13) + 'Dans les transports en commun (aérien, maritime, terrestre) ainsi que dans les gares et les lieux publics, les micro-ordinateurs portables et les tablettes tactiles sont garantis sous réserve qu''ils soient sous la surveillance directe et immédiate de l''assuré ou des personnes qui l''accompagnent.' + CHAR(13) + 'Au cours des transports effectués pour son propre compte par l''assuré ou les membres de sa société, sont exclus les vols dans les véhicules en stationnement :' + CHAR(13) + '- des biens visibles de l''extérieur du véhicule,' + CHAR(13) + '- commis dans un véhicule qui ne serait pas totalement carrossé en matériaux durs et fermé à clef,' + CHAR(13) + '- commis entre 21h et 7h, lorsque le véhicule est en stationnement sur la voie publique.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA13','Conditions de garantie vol des brises-roches ',1,'Par dérogation aux Conditions générales, est garanti le vol du brise-roche :' + CHAR(13)  + CHAR(13) + '- par démontage sur un engin,' + CHAR(13) + '- non monté sur un engin ou entreposé au sol, et qui fait suite à une effraction ou violence.' + CHAR(13) + 'La franchise en cas de vol sera égale à 5% de la valeur de remplacement à neuf du brise-roche, au jour du sinistre, avec un minimum de 800 euros')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA14','Dispositions applicables aux sources d''émission ou de réception',0,'Conformément aux Conditions générales, ne sont pas garantis les dommages limités aux pièces, éléments ou outils, ou composants de machines qui nécessitent de par leur fonctionnement un remplacement périodique.' + CHAR(13)  + CHAR(13) + 'Ces dispositions s’appliquent notamment aux organes mettant en œuvre des phénomènes électromagnétiques, tels que :' + CHAR(13) + '- la lumière : lampes, cellules photosensibles' + CHAR(13) + '- le laser : tubes d’émission, cellules de réception' + CHAR(13) + '- le rayonnement ultra-violet : tubes fluorescents, lampes ultra-violet' + CHAR(13) + '- les rayonnements ionisants : tubes Geiger-Müller, détecteurs à semi-conducteur' + CHAR(13) + '- les capteurs, détecteurs numériques fixes ou amovibles.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA15','Franchise en cas de dommage consécutif aux effets de la foudre',0,'Dans le cas où la machine n''est pas, au jour du sinistre, munie d''une installation de protection contre la foudre (parafoudre, parasurtenseur, onduleur), la franchise de base précisée dans l’inventaire des biens assurés est doublée en cas de dommages consécutifs à des effets de la foudre.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA17','Franchise applicable en cas d’incendie prenant naissance dans la machine ',0,'Dans le cas où la machine utilise un hydrocarbure comme liquide diélectrique, la franchise, en cas de dommages consécutifs à un incendie ayant pris naissance dans la machine, sera égale à 10% du montant des dommages si la machine n''est pas équipée d''un dispositif de sécurité en fonctionnement provoquant l''arrêt de la machine en cas de baisse de niveau ou d’élévation anormale de température du liquide diélectrique et le déclenchement d''une installation d''extinction automatique.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA18','Définition du bien assuré ',0,'Sont assurés, sans inventaire détaillé, tous les équipements constituant l''installation téléphonique (tels que autocommutateur, central, standard, postes individuels, les câbles de liaison, les  équipements d''alimentation électrique, transformateur, redresseur, onduleur, batterie).' + CHAR(13)  + CHAR(13) + 'La valeur déclarée doit correspondre à la valeur globale de cette installation.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA20','Utilisation sur la voie publique ',0,'La garantie est étendue, dans les limites du contrat, aux dommages subis par la machine lorsqu''elle se trouve sur la voie publique à proximité de l''adresse du risque sous réserve qu''elle soit remisée le soir après la fermeture dans un local entièrement clos.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA22','Exclusion des produits ou espèces ',0,'Il est rappelé que la garantie s''applique uniquement aux éléments constituant la machine.' + CHAR(13)  + CHAR(13) + 'En conséquence, ne sont pas garantis les produits ou les espèces contenus dans le bien assuré.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA23','Dispositions applicables aux sources d''émission ou de réception (médical)',0,'Conformément aux Conditions générales, ne sont pas garantis les dommages limités aux pièces, éléments ou outils, ou composants de machines qui nécessitent de par leur fonctionnement un remplacement périodique.' + CHAR(13)  + CHAR(13) + 'Ces dispositions s’appliquent aux sources d’émission ou de réception d’ondes électromagnétiques, acoustiques ou électroacoustiques comme :' + CHAR(13) + 'a) les organes mettant en œuvre des phénomènes électromagnétiques, tels que :' + CHAR(13) + '- lumière : lampes, cellules photosensibles' + CHAR(13) + '- laser : tubes d’émission, cellules de réception' + CHAR(13) + '- ultra-violet : tubes fluorescents, lampes ultra-violet' + CHAR(13) + '- rayons x : tubes d’émission, détecteurs silicium-lithium' + CHAR(13) + '- rayonnements ionisants : tubes Geiger-Muller, détecteurs à semi-conducteur' + CHAR(13) + '- les capteurs, détecteurs numériques fixes ou amovibles,' + CHAR(13) + 'b) les organes mettant en œuvre des phénomènes acoustiques ou électroacoustiques, tels que :' + CHAR(13) + '- sons et ultra-sons : transducteurs, sondes d’échographe, microphones.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA26','Exclusion de travaux réalisés chez les ferrailleurs',0,'La garantie du contrat ne s’applique pas dans le cas où la machine est utilisée pour effectuer des travaux de récupération des vieux métaux et de démolition de voitures.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA28','Dispositions spécifiques aux véhicules porteurs ',0,'Les véhicules porteurs (carrosserie, cabine, châssis, moteur, transmission, essieux, suspension, roues) sont garantis sous réserve que leurs valeurs soient incluses dans les capitaux assurés.' + CHAR(13)  + CHAR(13) + '' + CHAR(13) + 'Par dérogation aux Conditions générales :' + CHAR(13) + '' + CHAR(13) + 'La garantie pour les véhicules porteurs est limitée à tout dommage matériel résultant :' + CHAR(13) + '- d’un accident de circulation, d’une collision, d’un choc contre un corps fixe ou mobile,' + CHAR(13) + '- d’un renversement, d’un effondrement, d’un affaissement de terrain,' + CHAR(13) + '- d’une chute à l’eau, d’un contact avec des fumées, liquide ou gaz' + CHAR(13) + '- d’un incendie, d’une explosion,' + CHAR(13) + '- d’un vol, d’un vandalisme,' + CHAR(13) + '- d’un événement naturel,' + CHAR(13) + '- d’un attentat ou actes de terrorisme.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA29','Solidification du béton ',0,'En cas de sinistre, nous garantissons les dommages résultant de la solidification du béton transporté et qui sont la conséquence d’un dommage matériel garanti atteignant la machine assurée, ou qui fait suite à un accident de circulation.' + CHAR(13)  + CHAR(13) + 'Au titre de ces dommages, nous prenons en charge :' + CHAR(13) + '- la réparation de la machine sinistrée,' + CHAR(13) + '- la perte du béton solidifié pour un montant maximum de 1500 euros,' + CHAR(13) + '- les frais engagés pour retirer le béton solidifié dans la limite de 5% du capital assuré sur la machine sinistrée.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA30','Exclusion du porteur',0,'Il est précisé que le porteur (carrosserie, cabine, châssis, moteur, transmission, essieux, suspension, roues) du bien assuré est exclu de la garantie.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA31','Définition de l’installation assurée',0,'Sont assurés, sans inventaire détaillé, tous les équipements constituant l''installation de balnéothérapie (équipement électromécanique, baignoire, ...).' + CHAR(13)  + CHAR(13) + 'La valeur déclarée doit correspondre à la valeur globale de cette installation.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA33','Définition du bien assuré ',0,'Sont assurés sans inventaire détaillé tous les équipements, accessoires et d''une façon générale tous les éléments constituant l''installation.' + CHAR(13)  + CHAR(13) + 'La valeur déclarée doit correspondre à la la valeur de remplacement à neuf de l''ensemble de' + CHAR(13) + 'l''installation.' + CHAR(13) + 'Vous devez en cas de sinistre, nous donner tout justificatif de l''exactitude de la déclaration des capitaux (factures, inventaires ...).' + CHAR(13) + 'S''il était constaté que la valeur assurée était insuffisante, vous supporteriez la réduction d''indemnité prévue à l''Article L.121.5 du Code des assurances.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA34','Solidification de la matière',0,'En cas de sinistre, nous garantissons les dommages résultant de la solidification des produits ou matière en cours de fabrication ou de traitement et qui sont la conséquence d’un dommage matériel garanti atteignant la machine assurée.' + CHAR(13)  + CHAR(13) + 'Au titre de ces dommages, nous prenons en charge :' + CHAR(13) + '- la réparation de la machine sinistrée,' + CHAR(13) + '- la perte de produits ou matière en cours de fabrication ou traitement pour un montant maximum de 1500 euros,' + CHAR(13) + '- les frais engagés pour retirer les produits ou matière solidifiés dans la limite de 5% du capital assuré sur la machine sinistrée.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA36','Disposition en cas de non utilisation des dispositifs de sécurité ',0,'Lorsque le sinistre résulte, ou est aggravé, par la mise hors service ou la non utilisation d''un des dispositifs de sécurité équipant l''engin, et que les conditions d''exploitation du matériel nécessitaient l''utilisation des systèmes de sécurité, la franchise précisée ci-avant aux présentes Conditions Particulières sera portée à 10% du montant du dommage avec un minimum égal à 2 fois la franchise de base précisée dans l’inventaire des biens assurés.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA38','Vétusté sur les pièces ou organes sujets à usure ',0,'Sur les pièces ou organes sujets à usure, notamment les tuyaux, flexibles, pneurides, tapis, vessies, membranes, une vétusté est appliquée en fonction du rapport existant entre la durée de fonctionnement réelle depuis leur dernier remplacement et leur durée de vie normale.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA40','Extension au vol sans effraction ',1,'Par dérogation aux Exclusions générales des Conditions générales, la garantie est étendue au vol sans effraction ou violence. Elle s''exerce à l''adresse du risque dans les bâtiments d''exploitation et cours attenantes.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA47','Exclusions applicables aux sources d''émission ou de réception ',0,'Conformément aux Conditions générales, ne sont pas garantis les dommages limités aux pièces, éléments ou outils, ou composants de machines qui nécessitent de par leur fonctionnement un remplacement périodique.' + CHAR(13)  + CHAR(13) + 'Ces dispositions s’appliquent notamment aux : lampes, lasers (tube d’émission, cellules de réception), transducteurs.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA48','Dispositions spécifiques aux sondes d''échographie ',0,'Les dommages aux sondes d’échographe désignées au contrat ne donnent lieu à indemnisation que s’ils résultent d’un incendie, d’un vol, d’une chute, d’un choc, d’un dégât des liquides, ou d’un événement n’ayant aucun rapport avec leur usure ou leur dépréciation naturelle.' + CHAR(13)  + CHAR(13) + 'En cas de dommage garanti atteignant une sonde et limité à celle-ci, il sera appliqué une vétusté de 2 % par mois à compter de la date de 1ère mise en service. Cette vétusté est plafonnée à 80 %.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA51','Exclusion des défibrillateurs à usage public ',0,'La garantie ne s''applique pas lorsque le défibrillateur est à usage public.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA52','Extension des défibrillateurs à usage public ',1,'La garantie est étendue à un usage public du défibrillateur. Par dérogation aux Conditions générales nous garantissons le vol commis avec ou sans effraction, avec ou sans violence. En cas de vol la franchise de base indiquée ci-avant dans l’inventaire des biens assurés est multipliée par 2.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA53','Dispositions spécifiques aux enneigeurs ',0,'Franchise applicable aux enneigeurs dans le cas d''un sinistre résultant d''une avalanche artificielle, déclenchée volontairement :' + CHAR(13)  + CHAR(13) + 'Outre la franchise générale du contrat toujours déduite de l''indemnisation, en cas de dommages aux enneigeurs suite à avalanche artificielle déclenchée volontairement, nous n''indemniserons les enneigeurs qu''à compter du sixième enneigeur sinistré.' + CHAR(13) + 'Si moins de six enneigeurs sont sinistrés, aucune indemnisation n''est due à l''assuré au titre des enneigeurs.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA54','Extension de garantie relative aux inondations ',0,'Par dérogation aux exclusions générales des Conditions générales, sont garantis les dommages causés par les inondations provenant des cours d''eau ou d''étendues d''eau, même si elles ne sont pas déclarées catastrophes naturelles.' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA59','Dispositions spécifiques aux échafaudages ',1,'Par dérogations aux Conditions générales :' + CHAR(13)  + CHAR(13) + '- le vol des échafaudages est garanti, avec ou sans effraction ou violence, à condition que les' + CHAR(13) + '  échafaudages soient montés,' + CHAR(13) + '- le vol des échafaudages entreposés au sol sur les lieux de chantier ou dans un véhicule au cours' + CHAR(13) + '  des déplacements ou sur les chantiers est exclu,' + CHAR(13) + 'Conformément aux Conditions générales :' + CHAR(13) + '- le vol des échafaudages dans vos locaux propres est garanti à condition qu’il ait été commis avec' + CHAR(13) + '  effraction, ou violence.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA60','Conditions de garantie Vol des banches et coffrages',1,'Conformément aux Conditions générales :' + CHAR(13)  + CHAR(13) + '- le vol des banches ou coffrages dans vos locaux ou entreposés dans un véhicule est garanti, à' + CHAR(13) + '  condition qu’il ait été commis avec effraction, ou violence.' + CHAR(13) + 'Par dérogations aux Conditions générales :' + CHAR(13) + '- le vol des banches ou coffrages est garanti sur les lieux de chantier, avec ou sans effraction ou violence. ')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA61','Exclusions relatives à la garantie vol ',1,'En complément des exclusions générales, nous ne garantissons pas :' + CHAR(13)  + CHAR(13) + '1) les pertes et les disparitions inexpliquées ;' + CHAR(13) + '2) les vols commis sans menace, sans agression, ou sans effraction des locaux ou des véhicules dans lesquels se trouvent les biens assurés ;' + CHAR(13) + '3) les vols survenus dans un lieu public (*) des appareils laissés sans surveillance directe et immédiate de l''assuré ou des personnes qui l''accompagnent.' + CHAR(13) + '(*) notamment les transports en commun, les gares et les aéroports ;' + CHAR(13) + '4) le vol des appareils laissés dans un véhicule, si le vol n''est pas consécutif à une effraction du' + CHAR(13) + 'véhicule, ou au vol du véhicule, ou à un accident de circulation ;' + CHAR(13) + '5) le vol des appareils laissés visibles de l''extérieur dans un véhicule en stationnement ;' + CHAR(13) + '6) le vol des appareils laissés dans un véhicule en stationnement, commis la nuit entre 22h00 et 7h00 du matin ;' + CHAR(13) + '7) les vols des appareils laissés dans un véhicule non totalement carrossé' + CHAR(13) + 'en matériaux durs ;' + CHAR(13) + '8) les vols limités aux accessoires et consommables (cartes mémoires, chargeurs, batteries, sacs de protection,...). Les objectifs ne sont pas considérés comme des accessoires.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA62','Exclusions relatives à la garantie dommages ',0,'En complément des exclusions des Conditions générales sont exclus :' + CHAR(13)  + CHAR(13) + '1) les dommages se limitant aux seuls accessoires (cartes mémoires, batteries, chargeurs, trépieds,....). Les objectifs ne sont pas considérés comme des accessoires ;' + CHAR(13) + '2) les dommages qui sont pris en charge dans le cadre de la garantie "constructeur".' + CHAR(13) + '3) les dommages d''ordre esthétique causés aux parties extérieures de l''appareil ne nuisant pas à son bon fonctionnement (par exemple : les rayures, éraflures, écaillures, piqûres, tâches) ;' + CHAR(13) + '4) les dommages aux appareils non pris en bagage à main dans les transports en commun (terrestre, aérien ou maritime).')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA63','Détermination de l’indemnité – application d’une vétusté forfaitaire  ',0,'Par dérogation aux Conditions générales :' + CHAR(13)  + CHAR(13) + 'En cas de sinistre partiel : sans pouvoir excéder la somme fixée si nécessaire par expertise, le montant de l''indemnité est égal aux frais de réparation, sans application de vétusté ;' + CHAR(13) + 'En cas de sinistre total : sans pouvoir excéder la somme fixée si nécessaire par expertise, le montant de l''indemnité est égal :' + CHAR(13) + '- pendant les trois premières années suivant la date de première mise en service : à la valeur de remplacement à neuf au jour du sinistre,' + CHAR(13) + '- après les trois premières années suivant la date de première mise en service : à la valeur de remplacement à neuf au jour du sinistre déduction faite d''une vétusté de 0,70% par mois depuis la date de première mise en service. Cette vétusté est limitée à 60%.' + CHAR(13) + 'Il sera toujours fait déduction de la franchise et des valeurs de sauvetage s''il y a lieu.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA65','Condition de garantie des capteurs / détecteurs numériques ',0,'Les dommages aux capteurs / détecteurs numériques désignés au contrat ne donnent lieu à indemnisation que s’ils résultent d’un incendie, d’un vol, d’une chute, d’un choc, ou d’un événement n’ayant aucun rapport avec leur usure ou leur dépréciation naturelle.' + CHAR(13)  + CHAR(13) + 'En cas de dommage garanti il sera appliqué une vétusté :' + CHAR(13) + '- de 2% par mois suivant la date de 1ère mise en service. Cette vétusté est plafonnée à 80%.' + CHAR(13) + 'Franchise : en cas de sinistre limité à un capteur / détecteur numérique il sera déduit de l’indemnité une franchise égale à 5% de la valeur de remplacement à neuf du capteur / détecteur sinistré.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA67','Conditions de garantie vol ',1,'Le matériel est garanti en tous lieux sous réserve :' + CHAR(13)  + CHAR(13) + '- qu’en dehors des marchés, le matériel soit remisé dans un endroit clos et fermé à clef.' + CHAR(13) + 'Franchise spécifique en cas de vol :' + CHAR(13) + '- en cas de vol, la franchise de base indiquée ci-avant dans l’inventaire des biens assurés est multipliée par 5.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA70','Exclusion des pertes de liquide ou de gaz ',0,'Sont exclus toutes pertes d’héium se présentant sous format liquide ou gazeux qui ne font pas suite à un dommage accidentel ayant endommagé d’autres parties de la machine. Sont notamment exclus la perte d’hélium :' + CHAR(13)  + CHAR(13) + '- par défaut s’isolation dans le système thermique,' + CHAR(13) + '- par déclenchement volontaire de l‘évacuation de l’hélium de la cuve,' + CHAR(13) + '- par activation du dispositif de sécurité déclenché par le personnel, volontairement ou involontairement.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA90','Conditions de garantie vol ',1,'Il est rappelé que conformément aux Conditions générales, seuls sont garantis les vols qui ont été  commis avec effraction ou violence.' + CHAR(13)  + CHAR(13) + '' + CHAR(13) + 'Cas particuliers  des engins et matériels de valeurs de remplacement à neuf supérieures à 25 000 € :' + CHAR(13) + 'Par dérogation aux Conditions générales, pour les engins et matériels d''une valeur de remplacement à neuf au jour de la souscription supérieure à 25000 euros, la garantie vol est étendue au vol sans effraction ou violence.')
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA91','Franchise spécifique vol ',1,'La franchise en cas de vol est portée à 5% de la valeur de remplacement à neuf au jour de la souscription / du sinistre ? de l''engin et/ou matériel volé avec un minimum égal à la franchise de base indiquée dans le paragraphe « Inventaire des biens assurés ».' + CHAR(13) )
INSERT INTO [sch_mchn].[T_EDITION_CLAUSE] ([CODE],[LABEL],[VOL],[CONTENT]) VALUES ('MA92','Conditions de garantie des outils',1,'Les vols d’outils utilisés par les engins (godet, grappin, brise-roche, marteau, cisaille,...) sont garanties aux conditions suivantes :' + CHAR(13)  + CHAR(13) + 'Conformément aux Conditions générales, les vols d’outils utilisés par les engins, non montés sur les engins ou entreposés au sol, sont garantis à condition qu’ils aient été commis avec effraction ou violence.' + CHAR(13) + 'Par dérogation aux Conditions générales la garantie vol des outils montés sur les engins est étendue au vol sans effraction ou violence.' + CHAR(13) + '' + CHAR(13) + 'Franchise spécifique vol :' + CHAR(13) + 'En cas de vol limité aux outils (godet, grappin, brise-roche, marteau, cisaille,...), la franchise sera égale à 5% de la valeur de remplacement à neufs  au jour du sinistre, du ou des outils volés, avec un minimum de 800 euros.')
