-------------------------------------------------------------------------
-- Auteur    : S838981
-- Date      : 08/12/2021
-- Base      : Sql Server - mchn
-- Version	 : 1.0.0
-- Projet	 : OSE BDM
-- Objet     : Ajout d'une machine manquante
-------------------------------------------------------------------------
USE [mchn]

DELETE [sch_mchn].[T_PRICING_RATE] WHERE [FK_MACHINE_ID] IN (SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022')
DELETE FROM [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE LIKE '65022';
DELETE FROM [sch_mchn].[T_FAMILYT_MACHINE_SPECIFICATION] WHERE [T_MACHINE_SPECIFICATIONMACHINE_ID] IN (SELECT [MACHINE_ID] FROM [sch_mchn].[T_MACHINE_SPECIFICATION] where [CODE] LIKE '65022');

INSERT INTO [sch_mchn].[T_MACHINE_SPECIFICATION] ([CODE],[NAME],[LABEL],[DESCRIPTION],[KEYWORDS],[SCORE],[IS_OUT_OF_MACHINE_INSURANCE],[IS_DELEGATED],[IS_UNREFERENCED],[IS_EXCLUDED],[AGE_LIMIT_ALLOWED],[START_DATETIME_SUBSCRIPTION_PERIOD],[END_DATETIME_SUBSCRIPTION_PERIOD],[MACHINE_RATE],[ALL_PLACE_CORVERED],[PRODUCT],[IS_TRANSPORTABLE]) VALUES  ('65022','Objectif photographique','Objectif photographique','Accessoire composé de plusieurs lentilles et permettant de donner des images réelles sur la surface sensible d’un appareil photo.','Téléobjectif|Focale|Zoom','0',0,1,0,0,2,'2022/06/01',null,35,'INCLUDED','INVENTAIRE',0)

UPDATE [sch_mchn].[T_MACHINE_SPECIFICATION] SET [EDITION_CLAUSE_CODES]='MA62|MA75|MA61' WHERE CODE='65022';

INSERT INTO [sch_mchn].[T_FAMILYT_MACHINE_SPECIFICATION]  ([T_FAMILYFAMILY_ID] ,[T_MACHINE_SPECIFICATIONMACHINE_ID])    VALUES   ((SELECT FAMILY_ID FROM [sch_mchn].[T_FAMILY] WHERE CODE='70' AND SUB_CODE ='10'),(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('GTL',1,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('INC',20,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('VOL',20,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('BDI',10,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('ADE',50,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='65022' AND START_DATETIME_SUBSCRIPTION_PERIOD='2022/06/01'))

