-------------------------------------------------------------------------
-- Auteur    : S838981
-- Date      : 28/11/2022
-- Base      : Sql Server - mchn
-- Version	 : 1.0.0
-- Projet	 : OSE BDM
-- Objet     : Ajout des colonnes pour le parc
------------------------------------------------------------------------- 
USE [mchn]

CREATE TABLE [sch_mchn].[T_RISK_PRECISION](
	[RISK_PRECISION_ID] [uniqueidentifier] NOT NULL,
	[MACHINE_CODE] [varchar](5) NOT NULL,
	[CODE] [varchar](50) NOT NULL,	
	[LABEL] [nvarchar](150) NULL,
	[DETAIL] [nvarchar](500) NULL,
 CONSTRAINT [PK_RISK_PRECISION_ID] PRIMARY KEY CLUSTERED 
(
	[RISK_PRECISION_ID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [sch_mchn].[T_RISK_PRECISION] ADD  DEFAULT (newid()) FOR [RISK_PRECISION_ID]
GO


ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [DEDUCTIBLE_MIN_VALUE] [int] NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [DEDUCTIBLE_MIN_INCLUDE] [bit] NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [DEDUCTIBLE_MAX_VALUE] [int] NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [DEDUCTIBLE_MAX_INCLUDE] [bit] NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [DEDUCTIBLE_UNIT] [varchar](5) NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [FINANCIAL_VALUATION_DELEGATED_MAX] [int] NULL; 
ALTER TABLE [sch_mchn].[T_MACHINE_SPECIFICATION] ADD [IS_FIRE_COVERAGE_MANDATORY] [bit] NULL; 


EXEC sp_rename '[sch_mchn].[T_MACHINE_SPECIFICATION].[EXTENDED_FLEET_COEVERAGE_ALLOWED_PERCENTAGE]', 'EXTENDED_FLEET_COVERAGE_ALLOWED_PERCENTAGE', 'COLUMN';