-------------------------------------------------------------------------
-- Auteur    : S838981
-- Date      : 03/04/2023
-- Base      : Sql Server - xbdm
-- Version	 : 1.0.0
-- Projet	 : OSE BDM
-- Objet     : insertion de nouvelles machines PV
-------------------------------------------------------------------------

DELETE [sch_mchn].[T_PRICING_RATE] WHERE [FK_MACHINE_ID] in (SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE in ('80007','80008','80009' ))
DELETE [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE [CODE] in ('80007','80008','80009')

INSERT INTO [sch_mchn].[T_MACHINE_SPECIFICATION]([CODE],[NAME],[LABEL],[SCORE],[IS_OUT_OF_MACHINE_INSURANCE],[IS_DELEGATED],[IS_UNREFERENCED],[IS_EXCLUDED],[START_DATETIME_SUBSCRIPTION_PERIOD],[END_DATETIME_SUBSCRIPTION_PERIOD],[MACHINE_RATE],[ALL_PLACE_CORVERED],[PRODUCT],[DEDUCTIBLE_MIN_VALUE],[DEDUCTIBLE_MIN_INCLUDE],[DEDUCTIBLE_MAX_VALUE],[DEDUCTIBLE_MAX_INCLUDE],[DEDUCTIBLE_UNIT],[AGE_LIMIT_ALLOWED],[EDITION_CLAUSE_CODES]) VALUES ('80007',N'Installation en panneaux souples et membranes flexibles',N'Installation souple','7',0,1,0,1,'01/01/2023',null,0,'POINTLESS','PHOTOVOLTAIC',500,1,5000,1,'EUR',12,null)
INSERT INTO [sch_mchn].[T_MACHINE_SPECIFICATION]([CODE],[NAME],[LABEL],[SCORE],[IS_OUT_OF_MACHINE_INSURANCE],[IS_DELEGATED],[IS_UNREFERENCED],[IS_EXCLUDED],[START_DATETIME_SUBSCRIPTION_PERIOD],[END_DATETIME_SUBSCRIPTION_PERIOD],[MACHINE_RATE],[ALL_PLACE_CORVERED],[PRODUCT],[DEDUCTIBLE_MIN_VALUE],[DEDUCTIBLE_MIN_INCLUDE],[DEDUCTIBLE_MAX_VALUE],[DEDUCTIBLE_MAX_INCLUDE],[DEDUCTIBLE_UNIT],[AGE_LIMIT_ALLOWED],[EDITION_CLAUSE_CODES]) VALUES ('80008',N'Installation aérovoltaïque',N'Centrale aérovoltaïque','8',0,1,0,1,'01/01/2023',null,0,'POINTLESS','PHOTOVOLTAIC',500,1,5000,1,'EUR',12,null)
INSERT INTO [sch_mchn].[T_MACHINE_SPECIFICATION]([CODE],[NAME],[LABEL],[SCORE],[IS_OUT_OF_MACHINE_INSURANCE],[IS_DELEGATED],[IS_UNREFERENCED],[IS_EXCLUDED],[START_DATETIME_SUBSCRIPTION_PERIOD],[END_DATETIME_SUBSCRIPTION_PERIOD],[MACHINE_RATE],[ALL_PLACE_CORVERED],[PRODUCT],[DEDUCTIBLE_MIN_VALUE],[DEDUCTIBLE_MIN_INCLUDE],[DEDUCTIBLE_MAX_VALUE],[DEDUCTIBLE_MAX_INCLUDE],[DEDUCTIBLE_UNIT],[AGE_LIMIT_ALLOWED],[EDITION_CLAUSE_CODES]) VALUES ('80009',N'Installation en façade',N'Installation en façade','9',1,1,0,0,'01/01/2023',null,0,'POINTLESS','PHOTOVOLTAIC',500,1,5000,1,'EUR',12,null)

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('GTL',1,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80007' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('GTL',1,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80008' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('GTL',1,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80009' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('VOL',25,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80007' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('VOL',25,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80008' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('VOL',25,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80009' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('BDI',10,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80007' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('BDI',10,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80008' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('BDI',10,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80009' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('ADE',15,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80007' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('ADE',15,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80008' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('ADE',15,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80009' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))

INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('INC',50,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80007' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('INC',50,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80008' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))
INSERT INTO [sch_mchn].[T_PRICING_RATE] ([CODE],[RATE],[FK_MACHINE_ID]) VALUES ('INC',50,(SELECT MACHINE_ID from [sch_mchn].[T_MACHINE_SPECIFICATION] WHERE CODE ='80009' AND START_DATETIME_SUBSCRIPTION_PERIOD='01/01/2023'))

